//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class centrosaludEntities : DbContext
    {
        public centrosaludEntities()
            : base("name=centrosaludEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cita> citas { get; set; }
        public virtual DbSet<especialidad> especialidads { get; set; }
        public virtual DbSet<especialista> especialistas { get; set; }
        public virtual DbSet<especialistashacenespecialidade> especialistashacenespecialidades { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
    }
}
