//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        
        public cita()
        {
            
        }

        public int idpaciente { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public int idcita { get; set; }

        public virtual paciente paciente { get; set; }
        public virtual especialistashacenespecialidade especialistashacenespecialidade { get; set; }

        public cita(int idPaciente, especialistashacenespecialidade especialista, TimeSpan horaTime, DateTime time)
        {
            this.idpaciente = idPaciente;
            this.fecha = time;
            this.hora = horaTime;
            this.especialistashacenespecialidade = especialista;
        }
    }
}
